### ISSUE TITLE
Can't toggle if it is billable or not

### ISSUE THREAD

**Issue by anorgan** [AM2studio/AM2-Time-Tracking-Chrome#1]
Makes me go into CRM and toggle the "Is Billable" on for my entries, so makes this extension pointless

Also, is billable should be on by default

**Comment by goranefbl** [comment]
Ok, fix coming today: 
- is billable will be on by default, 
- Ill remove billable hours as those are 99% same, PMs are the ones that usually change this.

**Comment by goranefbl** [comment]
#2
